timeplusd:
  tag: 3.0.2
  storage:
    stream:
      className: standard-rwo
      size: 150Gi
      selector: null
    history:
      className: standard-rwo
      size: 100Gi
      selector: null
    log:
      className: standard-rwo
      size: 100Gi
      selector: null
  config:
    stream_state_log:
      collect_interval_milliseconds: 15000
      flush_interval_milliseconds: 10000
    stream_metric_log:
      collect_interval_milliseconds: 15000
      flush_interval_milliseconds: 10000
    data:
      datastore:
        log:
          preallocate: false
  resources:
    limits:
      cpu: "15"
      memory: "32Gi"
      ephemeral-storage: "10Gi"
    requests:
      cpu: "2"
      memory: "2Gi"
      ephemeral-storage: "10Gi"
  service:
    clusterIP: None

timeplusAppserver:
  tag: 3.0.21
